### ISSUE TITLE
How can I use this to replace Gulp in our project?

### ISSUE THREAD

**Issue by abhisheksoni27** [omeid/gonzo#5]
I have a production application where we have the following pipelines and currently use gulp to execute them:

(Dev)
1. Compile SCSS files to CSS files.
2. Concatenate and Babelify JS files from folderA to folderB

(Production)
1. Minify CSS files and copy them to /FINAL/css directory
2. Minify JS files in /folderB to /FINAL/js directory

Given the size of the project, gulp has proven to be a bit on the slow side and we are thinking about other ways of compiling the assets.

Your project looks awesome to me. However, can you elaborate how would I go about using this to migrate from gulp to gonzo?

**Comment by omeid** [comment]
Hello @abhisheksoni27,

Gonzo is a general purpose file processing pipeline, there is also a [stage](https://github.com/go-gonzo/scss) for processing scss and [js minification](https://github.com/go-gonzo/js).

You should have no problem with accomplishing this task.

As a side note, I think Webpack is definitely something worth considering as well, specially if you don't intend to distribute the pipeline as part of your product, in which case Gonzo affords you a much better "single binary" experience.
